### ISSUE TITLE
npz files

### ISSUE THREAD

**Issue by flynnamy** [Fayeben/GenerativeDiffusionPrior#1]
Hi, could you please share hdr_100_short_resolution_256.npz,hdr_100_medium_resolution_256.npz,hdr_100_long_resolution_256.npz and LOL_low_resolution_256.npz? Thanks! @Fayeben

**Comment by Fayeben** [comment]
Hi, you can modify imagenet_dataloader/save_random_images_hdr.py to obtain the .npz files.
And the .npz will be uploaded soon.

**Comment by Fayeben** [comment]
I have uploaded the .npz files. Please have a try!
https://drive.google.com/drive/folders/1Lvp6vjovXOa3vYv98evVSxsmGX_C9sgy?usp=sharing
