### ISSUE TITLE
[Undefined function error] in sample_x0_enhancement_low_light.py

### ISSUE THREAD

**Issue by CaptainEven** [Fayeben/GenerativeDiffusionPrior#11]
I found function 'general_cond_fn' undefined in the file sample_x0_enhancement_low_light.py

**Comment by Fayeben** [comment]
Hi, we do not use general_cond_fn to add conditions, while we use light_cond_fn for low light enhancement.
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/116b875db9b4b6c3bcc8adcfc7dbaedb607e1edb/scripts/sample_x0_enhancement_low_light.py#L77

**Comment by CaptainEven** [comment]
Thanks for the reply!
