### ISSUE TITLE
[Test Question]

### ISSUE THREAD

**Issue by CaptainEven** [Fayeben/GenerativeDiffusionPrior#12]
How to restore(test or inference) a image under multi-degradations uisng GDP? How to use the test scripts?

**Comment by Fayeben** [comment]
HI, you can use the following script to have a try! The usage of this script can be found in README
scripts/sample_x0_enhancement_HDR.py

**Comment by CaptainEven** [comment]
> HI, you can use the following script to have a try! The usage of this script can be found in README scripts/sample_x0_enhancement_HDR.py

Thanks for the answering! By th way, it seems need 3 LDR reference imgs as contidion?

**Comment by Fayeben** [comment]
Yes, for HDR recovery, we need three LDR reference images as conditions, including LDR-short, LDR-medium, and LDR-long.

**Comment by Feynben** [comment]
Since there are no more questions, I'll mark it closed. If you still have some questions, please feel free to ask. Thanks!

**Comment by finnn00** [comment]
Hello
I would like to ask how to directly test the LOL dataset using the pre-trained model. The image generation time is quite long when following the steps in the README... I would like to know the time required if testing directly. 
Looking forward to ur reply.

**Comment by finnn00** [comment]
> Hello I would like to ask how to directly test the LOL dataset using the pre-trained model. The image generation time is quite long when following the steps in the README... I would like to know the time required if testing directly. Looking forward to ur reply.

low-light image enhancement task
