### ISSUE TITLE
[Question] How to test an arbitrary single image?

### ISSUE THREAD

**Issue by CaptainEven** [Fayeben/GenerativeDiffusionPrior#13]

**Comment by CaptainEven** [comment]
Is there any easy way to test a single degraded image rather than a dataset?

**Comment by Fayeben** [comment]
Yes, you can prepare the single image with the following script:
scripts/imagenet_dataloader/save_random_images_hdr.py
It can process a single image, and will not change the size of image.

**Comment by Feynben** [comment]
Since there are no more questions, I'll mark it closed. If you still have some questions, please feel free to ask. Thanks!
