### ISSUE TITLE
Could you release the train.py and test.py?

### ISSUE THREAD

**Issue by uThevia** [Fayeben/GenerativeDiffusionPrior#14]
Thanks!
I would like to train your model on other tasks.

Having read your excellent work, I would like to learn more about the actual training process of the degradation model D.

**Comment by Fayeben** [comment]
Hi, thanks! 
The degradation model D is not trained, while it is randomly initialized and optimized during the sampling. The loss will back-propagate to update the parameters of degradation model D.
You can devise a degradation model D, then optimize the parameters when sampling.
If you have further questions, please feel free to comment.

**Comment by uThevia** [comment]
Thank you very much for your reply!
