### ISSUE TITLE
关于超分数据集npz文件

### ISSUE THREAD

**Issue by br-pp** [Fayeben/GenerativeDiffusionPrior#15]
/nvme/feiben/DDPM_Beat_GAN/evaluations/precomputed/biggan_deep_imagenet64.npz
请问这个文件在哪里可以下载呢？

**Comment by Fayeben** [comment]
Hi, I have uploaded this file to google, you can download it and have a try!
https://drive.google.com/file/d/1E5eNHoOZQO9acapH-QMy35u-QYBbtnIv/view?usp=sharing

**Comment by Feynben** [comment]
Since there are no more questions, I'll mark it closed. If you still have some questions, please feel free to ask. Thanks!
