### ISSUE TITLE
Code based on the patch section

### ISSUE THREAD

**Issue by Hikari6666** [Fayeben/GenerativeDiffusionPrior#16]
Hello, I am very interested in your work.
Can you tell me where the code for the proposed patch-based approach is?

**Comment by Fayeben** [comment]
Hi, we use the patch-based method for low-light enhancement and HDR recovery. Therefore, you can find the code in these two scripts.
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/116b875db9b4b6c3bcc8adcfc7dbaedb607e1edb/scripts/sample_x0_enhancement_low_light.py
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/116b875db9b4b6c3bcc8adcfc7dbaedb607e1edb/scripts/sample_x0_enhancement_HDR.py

**Comment by ChenhLiwnl** [comment]
Can you provide specific hints on which lines correspond to the operations of the patch section? I didn't quite understand this code, much gratitude!

**Comment by Feynben** [comment]
Yes, you can check this line 
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/b34494cd53e344a5c726e502f552cd7fb888aad0/scripts/guided_diffusion/gaussian_diffusion_x0_enhancement_direct.py#L455C1-L455C1
