### ISSUE TITLE
result of Super-resolution with GDP-xt getting worse?

### ISSUE THREAD

**Issue by Maydaybye** [Fayeben/GenerativeDiffusionPrior#20]
![0_label_999](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/75834797/ccf22be3-89d7-4dca-83c4-bb5992780d9d)
![0_label_999](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/75834797/eb6e3e84-3e5e-470c-890d-9f02f28b2907)
First image is the original image from biggan_deep_trunc1_imagenet256.npz stored in the lr folder. And the second is sampled image stored in the images folder as sample_sr4.py delineate
I run the script 
(MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond False --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
python sample_sr4.py  $MODEL_FLAGS --use_img_for_guidance --start_from_scratch --save_png_files)
So the result is getting worse?

**Comment by Feynben** [comment]
Hi, "sample_sr4.py" is corresponding to our GDP-xt. You can try sample_x0_sr4.py, which is better than GDP-xt.
