### ISSUE TITLE
Can this Diffusion Model do Inpainting and Super-resolution at the same time?

### ISSUE THREAD

**Issue by SangHunHan92** [Fayeben/GenerativeDiffusionPrior#22]
Hello.

I am looking for a model that can restore detailed normal maps that have been inpainted through diffusion models and at the same time super-resolution. I show you example of normal map.
![000](https://github.com/Fayeben/GenerativeDiffusionPrior/assets/38457117/773bd6e2-4f6f-43a3-b4e8-329b62541703)

I'm not familiar with Diffusion yet, but is it possible to do Super-resolution and Inpainting at the same time?

**Comment by Feynben** [comment]
Hi, 

Our methods can do multi-degraded restorations that only one degradation does damage to the content of the picture, such as Colorization + SR, Colorization + Inpainting, or Colorization + Deblur. 
In our methods, it will be relatively hard to do Super-resolution and Inpainting at the same time. We also have tried this experiment, but the results are not very satisfactory.
If you want to utilize Diffusion Model to solve this problem, it might be specifically designed.

**Comment by SangHunHan92** [comment]
Thank you for answer!

Can you recommend another Diffusion Model suitable for this method?
