### ISSUE TITLE
Extension for other types of inpainting tasks

### ISSUE THREAD

**Issue by jiliya1991** [Fayeben/GenerativeDiffusionPrior#24]
Great work! If I want to try the box-based inpainting tasks instead of 25%, how to extend the code? Thanks

**Comment by Feynben** [comment]
Yes, our inpainting script can be easily applied on box-based inpainting. You can change the degradation model in this line:
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/b34494cd53e344a5c726e502f552cd7fb888aad0/scripts/sample_x0_inp.py#L102C22-L102C22
