### ISSUE TITLE
base_samples (npz files) for Generative Diffusion Prior (GDP) for non-linear, blind, multi-guidance problems (Low light enhancement, HDR recovery)

### ISSUE THREAD

**Issue by benchoi93** [Fayeben/GenerativeDiffusionPrior#25]
I was trying to run "sample_x0_enhancement_HDR.py" and "sample_x0_enhancement_low_light.py" but encountered a problem that there is no base_sample.

Can you explain how to generate those base_samples, or upload the npz files you used for the experiments?

**Comment by Feynben** [comment]
I have uploaded the .npz files. Please have a try!
https://drive.google.com/drive/folders/1Lvp6vjovXOa3vYv98evVSxsmGX_C9sgy?usp=sharing

**Comment by benchoi93** [comment]
Thank you! Much appreciated!
