### ISSUE TITLE
More detailed instructions on how to run the code

### ISSUE THREAD

**Issue by shukkkur** [Fayeben/GenerativeDiffusionPrior#26]
Hey there!

Everyone praising your paper and code, but honestly I hardly understood anything. I saw some visuals and thought perhaps I could try to run this algorithm of a few images I have. However, with the instructions you left (for your fellow researchers probably) it is impossible for me to run or understand what is the problem. 

Can you please, please write a more detailed step-by-step instructions, on how to run the code on my own sample images. I am not interested in metrics or comparison across datasets, I just need to get output image and compare it with the original. 

More people could benefit from your work, and we would be grateful.

**Comment by Feynben** [comment]
Hello, since we are busy with our project, we are sorry for the late reply.  We will refine our README when we finish our current project. Thanks for your understanding.
