### ISSUE TITLE
How to get sr4_resolution_256.npz?

### ISSUE THREAD

**Issue by Clover698** [Fayeben/GenerativeDiffusionPrior#28]
Thanks for the authors' nice implementation.
I have run the codes for super-resolution and encountered the following error.
Could anyone tell me how to get the file "sr4_resolution_256.npz"?
Thank you very much!

`_FileNotFoundError: [Errno 2] No such file or directory: '/nvme/feiben/DDPM_Beat_GAN/scripts/imagenet_dataloader/sr4_resolution_256.npz_`

**Comment by Feynben** [comment]
Hi, since we are busy with our project, we are sorry for the late reply.  You can find the .npz files in https://drive.google.com/drive/folders/1Lvp6vjovXOa3vYv98evVSxsmGX_C9sgy?usp=drive_link
