### ISSUE TITLE
error

### ISSUE THREAD

**Issue by flynnamy** [Fayeben/GenerativeDiffusionPrior#5]
Hi, It has an error when I use MODEL_FLAGS="--attention_resolutions 32,16,8 --class_cond False --diffusion_steps 1000 --image_size 256 --learn_sigma True --noise_schedule linear --num_channels 256 --num_head_channels 64 --num_res_blocks 2 --resblock_updown True --use_fp16 True --use_scale_shift_norm True"
python sample_x0_enhancement_low_light.py  $MODEL_FLAGS --use_img_for_guidance --start_from_scratch --save_png_files this command. The error like this"File "/home/GenerativeDiffusionPrior-main/scripts/sample_x0_enhancement_low_light.py", line 103, in light_cond_fn
    mse = (x_in_lr - x_lr) ** 2
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3". I print the shape of the tensor and find that the x_in_lr is torch.Size([1, 3, 256, 256]) but x_lr is torch.Size([1, 3, 256, 128]). How to solve this? @Fayeben

**Comment by Fayeben** [comment]
Thanks for asking. May I ask about the size of low-light images?

**Comment by flynnamy** [comment]
256x256 and I save it to 256.npz. Should I use 400x600?

**Comment by flynnamy** [comment]
I try your LOL_resolution_256.npz and hava same error! @Fayeben

**Comment by Fayeben** [comment]
You can take the .npz that I upload to have a try.
The size of the light mask should be the same size as your low-light images.
You can modify this in 
https://github.com/Fayeben/GenerativeDiffusionPrior/blob/2dcd3c6f5b43c3dd20095611530be8ac21b07656/scripts/sample_x0_enhancement_low_light.py#L173

**Comment by Fayeben** [comment]
I upload new file named LOL_low_resolution_256.npz
Please try this one.

**Comment by flynnamy** [comment]
I change it to 256,256, same error.Info like this:
"Logging to results
creating model and diffusion...
loading dataset...
dataset LOL_resolution_256.npz:
input_data: (15, 3, 256, 256)
labels: (15,)
dummy dataset:
input_data: (15,)
results
sampling...
0 0
<built-in method size of Tensor object at 0x00000263380429D0>
step t 999 img guidance has been used, mse is 0.01359228 * 80000 = 1087.38
<built-in method size of Tensor object at 0x0000026338043010>
step t 999 img guidance has been used, mse is 0.01359228 * 80000 = 1087.38
0 128
Traceback (most recent call last):
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3"

**Comment by Fayeben** [comment]
Please use LOL_low_resolution_256.npz and our original code with only the file path modified, and have a try.

**Comment by Fayeben** [comment]
If you can run the script successfully, plz let me know. Thanks.

**Comment by flynnamy** [comment]
I try your HDR npz and lol npz files with enhance and HDR tasks.Same error.I found that it can run for some steps,then changed the shape from 256 to 128. Any suggestions? @Fayeben 
"Logging to results
creating model and diffusion...
loading dataset...
dataset hdr_100_short_resolution_256.npz:
input_data: (100, 3, 256, 256)
labels: (100,)
dataset hdr_100_medium_resolution_256.npz:
input_data: (100, 3, 256, 256)
labels: (100,)
dataset hdr_100_long_resolution_256.npz:
input_data: (100, 3, 256, 256)
labels: (100,)
dummy dataset:
input_data: (100,)
results
sampling...
<built-in method size of Tensor object at 0x7f5d1d034b80>
step t 999 img guidance has been used, mse is 0.02747772 * 80000 = 2198.22
<built-in method size of Tensor object at 0x7f5d1f544ea0>
step t 999 img guidance has been used, mse is 0.08410400 * 80000 = 6728.32
<built-in method size of Tensor object at 0x7f5d1d034b80>
step t 999 img guidance has been used, mse is 0.22840318 * 80000 = 18272.25
Traceback (most recent call last):
  File "/home/GenerativeDiffusionPrior-main/scripts/sample_x0_enhancement_HDR.py", line 284, in <module>
    main()
  File "/home/GenerativeDiffusionPrior-main/scripts/sample_x0_enhancement_HDR.py", line 191, in main
    sample, light_factor, light_mask = sample_fn(
  File "/home/GenerativeDiffusionPrior-main/scripts/guided_diffusion/gaussian_diffusion_x0_enhancement_HDR.py", line 552, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/GenerativeDiffusionPrior-main/scripts/guided_diffusion/gaussian_diffusion_x0_enhancement_HDR.py", line 634, in p_sample_loop_progressive
    out, light_factor, light_mask = self.p_sample(
  File "/home/GenerativeDiffusionPrior-main/scripts/guided_diffusion/gaussian_diffusion_x0_enhancement_HDR.py", line 470, in p_sample
    out["mean"], light_factor_tmp, light_mask_tmp = self.condition_mean(
  File "/home/GenerativeDiffusionPrior-main/scripts/guided_diffusion/respace_x0_enhancement.py", line 395, in condition_mean
    return super().condition_mean(self._wrap_model1(cond_fn), *args, **kwargs)
  File "/home/GenerativeDiffusionPrior-main/scripts/guided_diffusion/gaussian_diffusion_x0_enhancement_HDR.py", line 371, in condition_mean
    light_factor, light_mask, gradient = cond_fn(pred_xstart, self._scale_timesteps(t), light_factor=light_factor, light_mask=light_mask, corner=corner, **model_kwargs)
  File "/home/GenerativeDiffusionPrior-main/scripts/guided_diffusion/respace_x0_enhancement.py", line 343, in __call__
    return self.model(x, new_ts, light_factor, light_mask, corner, **kwargs)
  File "/home/GenerativeDiffusionPrior-main/scripts/sample_x0_enhancement_HDR.py", line 166, in <lambda>
    cond_fn_short = lambda x,t,light_factor,light_mask,corner,y : light_cond_fn(x, t, light_factor=light_factor, light_mask=light_mask, corner=corner, y=y, x_lr=image_lr_short, sample_noisy_x_lr=args.sample_noisy_x_lr, diffusion=diffusion, sample_noisy_x_lr_t_thred=args.sample_noisy_x_lr_t_thred)
  File "/home/GenerativeDiffusionPrior-main/scripts/sample_x0_enhancement_HDR.py", line 103, in light_cond_fn
    mse = (x_in_lr - x_lr) ** 2
RuntimeError: The size of tensor a (256) must match the size of tensor b (128) at non-singleton dimension 3"

**Comment by Fayeben** [comment]
Can you run the LOL dataset successfully?  I reupload NPZ files for HDR task. Please download the latest version. Thanks

**Comment by flynnamy** [comment]
I can run the latest version successfully. Thanks! @Fayeben

**Comment by Fayeben** [comment]
Since this issue has been solved, I will mark it as closed.
