### ISSUE TITLE
Apply to blind SR

### ISSUE THREAD

**Issue by Harper714** [Fayeben/GenerativeDiffusionPrior#8]
Hi, thanks for the excellent work.

I have read the paper, and it seems that the method can only be applied to a simple unknown degradation model with self-defined parameters (i.e., low-light enhancement described in eq. 10) ?
However, if we want to apply the model to more complicated degradations, such as blind SR or natural-image restoration, which are difficult to describe using a simple model with several parameters, then if the method will still work, or how to use the proposed method?

**Comment by Fayeben** [comment]
Hi! For more complicated degradations, such as blind SR or natural-image restoration, the type of degradation is still needed to be given, while the parameters of degradation can be optimized along the sampling. Multiple degradations are also supported. But we found that two or more degradations that damage the image content, such as SR and blur, will make the restoration more difficult. The multiple degradations, such as gray + SR, or low-light + SR can work well.

**Comment by Feynben** [comment]
Since there are no more questions, I'll mark it closed. If you still have some questions, please feel free to ask. Thanks!
